#
#Copyright Odin Solutions S.L. All Rights Reserved.
#
#SPDX-License-Identifier: Apache-2.0
#

version: '3.1'

services:
  authcomponents:
    image: iotcrawler/pap-pdp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
        - '8080:8080'
#        - '8443:8443'
    restart: unless-stopped
