# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  externalPort: 8080
  internalPort: 8080

livenessProbe:
  path: "/"
  initialDelaySeconds: 14
  timeoutSeconds: 14
  scheme: "HTTP"
readinessProbe:
  path: "/"
  initialDelaySeconds: 4
  timeoutSeconds: 2
  scheme: "HTTP"